### ISSUE TITLE
TBHM pop up change of behavior.

### ISSUE THREAD

**Issue by odoo-mvds** [applixodoo/grando-13#2]
Hello Rohan,

see attached screenshot. This information should be reflected on base type view.

![image](https://user-images.githubusercontent.com/59664044/73282631-35e03a80-41f2-11ea-86f7-6044f548b98f.png)

**Comment by odoo-mvds** [comment]
make both the TBHM field and TBHD field lockable.

**Comment by tidyway** [comment]
Branch  : td_grando_#4
Module : td_grando_keukens

Attached screenshots
![1) changed view with calculations](https://user-images.githubusercontent.com/10138854/73655762-b8666f80-46b4-11ea-882c-7e4c61125add.png)
![2) added field to base type](https://user-images.githubusercontent.com/10138854/73655775-c0beaa80-46b4-11ea-8e9c-1cf3fc221b86.png)
